### ISSUE TITLE
Don't reference dependencies by short commit hash

### ISSUE THREAD

**Issue by defuse** [zcash/zcash-android-wallet-sdk#362] opened 2022-01-12 20:10 UTC
Seen in the output of the build command...

```
  Compiling zcash_proofs v0.5.0 (https://github.com/gmale/librustzcash?branch=autoshield-poc-daa-taddr3#bd65b01e)
```

Kevin or someone who hacked him could change the contents of that branch (and make the start of the commit hash match) to backdoor an android release.

The proper fix to this is to:

1. Move this code onto a branch on our librustzcash fork
2. Reference the full commit hash, not just the first 32 bits

**Comment by ccjernigan** [comment] 2022-01-12 20:12
I think this is a duplicate of https://github.com/zcash/zcash-android-wallet-sdk/issues/248

**Comment by geffenz** [comment] 2022-01-12 21:08
There is also a DoS issue with the code being removed and breaking builds.

**Comment by str4d** [comment] 2022-01-12 22:23
We aren't referencing by short commit hash. The lockfile includes the full hash:
https://github.com/zcash/zcash-android-wallet-sdk/blob/38fd51519bd539f7bdbf336bf3700ed59708e24f/sdk-lib/Cargo.lock#L2035-L2037

The short hash is just for build output niceness.

**Comment by pacu** [comment] 2022-01-12 23:32
Do instead 

https://github.com/zcash/zcash-android-wallet-sdk/issues/363

**Closed by pacu** 2022-01-12 23:32 UTC
