### ISSUE TITLE
Demo-app binaries from CI are unsigned

### ISSUE THREAD

**Issue by HonzaR** [zcash/zcash-android-wallet-sdk#589] opened 2022-06-30 09:35 UTC
### Describe the issue
When we download the binaries zip of demo-app build variants, they all appear to be unassigned, and thus cannot be installed to any device (emulator devices nether).

#### If so, please list the steps to reproduce below:
1. Run CI task for building binaries
2. Download demo app binaries zip, (e.g. this one [Demo app release binaries](https://github.com/zcash/zcash-android-wallet-sdk/suites/7106370422/artifacts/281523753))
3. Unzip the archive
4. Try to install the demo-app on any device you have
5. Install error will show up

### Expected behaviour
We have all demo-app variants built by CI signed, so we can use them on any device.

- App Version: 
- Android Version:
- Device: (if applies)

### Any extra information that might be useful in the debugging process.
We should probably implement the signing process similarly as in the secant-wallet repository.

**Comment by ccjernigan** [comment] 2022-06-30 12:11
Duplicate of #522

**Closed by ccjernigan** 2022-06-30 12:11 UTC
Labels: bug
