### ISSUE TITLE
Feature Request: Support Custom Miners Fee + Add new receiver to transaction

### ISSUE THREAD

**Issue by nighthawk24** [zcash/zcash-android-wallet-sdk#159] opened 2020-08-26 18:17 UTC
Request:
To make the tx miners fee customizable and split the Network fee with the wallet/app, in line with the discussion to reduce fees for mobile P2P wallets, especially when sending MEMOs https://twitter.com/zooko/status/1295032621294956545?s=20

Additionally, enable adding a receiver when creating a new transaction, so the transaction fees from mobile wallets can be split between the miner fee + wallet maintainer to fund the servicing and upkeep of the mobile wallet software.

This change will enable self funding apps to be created and give users the piece of mind knowing that the wallet is being funded.

**Comment by gmale** [comment] 2020-08-31 13:54
As @nathan-at-least [mentioned here](https://twitter.com/least_nathan/status/1294359889981005824?s=20), I like the idea of creating some kind of "light-client working group" where it is easy to discuss these kinds of topics, with as much input as possible from key stakeholders.

Maybe it's worth trying to create that, first, and discuss this in more detail there.

Meanwhile, it sounds like a few key constraints will be:
- avoid fragmenting the anonymity set
- avoid leaking information about the transaction that wouldn't otherwise be available (i.e. fees based on value or increasing the number of inputs/outputs in ways that identify wallets)

**Comment by gmale** [comment] 2020-08-31 16:34
Update: working with Elena & Andre to put together a "light client" working group to discuss this topic and others. I'll update with more details once they've solidified.

**Comment by gmale** [comment] 2020-11-20 16:47
Update: light client working group has lead to [ZIP-313](https://github.com/zcash/zcash-android-wallet-sdk/issues/174) being created and implemented. The "Custom Miner's Fee" portion of this ticket can be considered closed as a duplicate of https://github.com/zcash/zcash-android-wallet-sdk/issues/174. The additional "Receiver" work would become possible after t-addr support and the data access API are completed.

**Comment by gmale** [comment] 2020-12-20 17:38
Update: ZIP-313 is implemented and functional. This ticket can be closed.

**Closed by gmale** 2020-12-20 17:38 UTC
